# Pre-commit configuration for Yesman-Claude project (Ruff-integrated version)
# Run with: pre-commit run --all-files

repos:
  # Python code formatting and linting with Ruff (replaces black, isort, flake8)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      # Linting (replaces flake8)
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --target-version=py311]
        exclude: ^(migrations/|node_modules/)
      # Formatting (replaces black)
      - id: ruff-format
        args: [--target-version=py311]
        exclude: ^(migrations/|node_modules/)

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(.*\.md|.*\.txt)$
      - id: end-of-file-fixer
        exclude: ^(.*\.md|.*\.txt)$
      - id: check-yaml
        exclude: ^(.github/|node_modules/)
      - id: check-json
        exclude: ^(node_modules/|package-lock\.json)
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: debug-statements
        exclude: ^(debug/|scripts/debug_)

  # Markdown formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        args: [--wrap=120]
        exclude: ^(node_modules/|tauri-dashboard/|\.github/workflows/)
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat-frontmatter

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML]
        files: ^(libs/|commands/|api/)
        args: [--config-file=pyproject.toml]

  # Security checks (optional: keep bandit for comprehensive security scanning)
  - repo: https://github.com/pycqa/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-r, -s, B101,B404,B603,B607,B602, --severity-level, medium, --quiet]
        exclude: ^(tests/|scripts/|debug/|docs/examples/|test_style_violation\.py)
        pass_filenames: false
        files: ^(libs/|commands/)

# Global configuration
default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit]

# CI configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
