# Default configuration for Yesman
# This file contains all default settings

# Core settings
mode: merge
root_dir: ~/.scripton/yesman

# Tmux configuration
tmux:
  default_shell: /bin/bash
  base_index: 0
  pane_base_index: 0
  mouse: true
  status_position: bottom
  status_interval: 1

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_path: ~/.scripton/yesman/logs/
  max_size: 10485760  # 10MB
  backup_count: 5

# Session management
session:
  sessions_dir: sessions
  templates_dir: templates
  projects_file: projects.yaml
  default_window_name: main
  default_layout: even-horizontal

# AI/LLM settings
ai:
  provider: anthropic
  model: claude-3-opus-20240229
  temperature: 0.7
  max_tokens: 4096
  api_key_env: ANTHROPIC_API_KEY

# Server settings
server:
  host: localhost
  port: 8000

# Database settings (disabled by default)
database:
  enabled: false
  url: sqlite:///~/.scripton/yesman/yesman.db
  pool_size: 5
  echo: false

# Other settings
confidence_threshold: 0.8
auto_cleanup_days: 30
enable_telemetry: false
